from constants import game_constants


SEEKER_SPAWN_COOLDOWN = 2000

# constantes do fight_seeker
FIGHT_SEEKER_RANGE = 60
FIGHT_SEEKER_HEALTH = 50
FIGHT_SEEKER_SPEED = 5
FIGHT_SEEKER_DAMAGE = 5
FIGHT_SEEKER_ARMOR = 0
