

SEEKER_SPAWN_COOLDOWN = 6000
SEEKER_SPAWN_INCREMENT = -800
SEEKER_SPAWN_TIME_LIMIT = 1800

# constantes do fight_seeker
FIGHT_SEEKER_RANGE = 60
FIGHT_SEEKER_HEALTH = int(30)
FIGHT_SEEKER_SPEED = 5
FIGHT_SEEKER_DAMAGE = 2
FIGHT_SEEKER_ARMOR = 0
SEEKER_WIDTH = 75
SEEKER_HEIGHT = 75
