from constants import game_constants


SPAWN_MARGIN = (30 / 100) * game_constants.SCREEN_HEIGHT
SEEKER_SPAWN_COOLDOWN = 1000

# constantes do fight_seeker
FIGHT_SEEKER_RANGE = 60
FIGHT_SEEKER_HEALTH = 100
FIGHT_SEEKER_SPEED = 5
FIGHT_SEEKER_DAMAGE = 5
FIGHT_SEEKER_ARMOR = 0
